// <auto-generated />
namespace Eva.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateEntityAtributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateEntityAtributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201805211423402_updateEntityAtributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
